# Generated by Django 3.0.6 on 2020-05-29 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0003_auto_20200529_2216'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.Company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.Contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.Outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Product')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Volume')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Warehouse')),
            ],
        ),
    ]
