# Generated by Django 3.0.6 on 2020-06-02 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.Outlet'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Volume'),
        ),
        migrations.AddField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Warehouse'),
        ),
    ]
