# Generated by Django 3.0.6 on 2020-06-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200602_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='number',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
