# Generated by Django 3.0.6 on 2020-05-29 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200529_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='warehouse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Warehouse'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='balance',
            name='product',
        ),
        migrations.AddField(
            model_name='balance',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='balance',
            name='volume',
        ),
        migrations.AddField(
            model_name='balance',
            name='volume',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Volume'),
            preserve_default=False,
        ),
    ]
