# Generated by Django 3.0.6 on 2020-05-25 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField(null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('upn', models.PositiveIntegerField(max_length=9, unique=True)),
                ('address', models.CharField(max_length=350)),
                ('email', models.EmailField(max_length=250)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Bank_account')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('birthday', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=30)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField(null=True)),
                ('due_date_payment', models.PositiveSmallIntegerField(default=45)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=4)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=350)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('contact', models.ManyToManyField(to='companies.Contact_person')),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.Service_area')),
            ],
        ),
        migrations.AddField(
            model_name='bank_account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Currency'),
        ),
    ]
