# Generated by Django 3.0.6 on 2020-05-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sales_plan', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
