# Generated by Django 3.0.6 on 2020-05-29 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_area',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='service_area',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service_area',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service_area',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service_area',
            name='sales_plan',
            field=models.PositiveIntegerField(unique_for_month=True),
        ),
        migrations.RemoveField(
            model_name='service_area',
            name='salesman',
        ),
        migrations.AddField(
            model_name='service_area',
            name='salesman',
            field=models.ManyToManyField(related_name='user_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
